[servers]
framework ansible_host=100.64.28.50 ansible_user=mark
carvell ansible_host=100.124.95.22 ansible_user=mark
fractal ansible_host=100.65.251.100 ansible_user=mark
cube ansible_host=100.69.61.62 ansible_user=mark
hennos ansible_host=100.118.11.78 ansible_user=mark
desktop ansible_host=100.104.126.88 ansible_user=mark
perlin ansible_host=100.109.46.40 ansible_user=mark
node ansible_host=100.120.225.70 ansible_user=mark
square ansible_host=100.110.116.40 ansible_user=mark
bridge ansible_host=100.103.61.82 ansible_user=mark
