---
- name: upgrade packages
  hosts: servers
  become: true
  become_method: sudo
  gather_facts: true

  tasks:
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: apt upgrade
      ansible.builtin.apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
