---
- hosts: test
  remote_user: root
  tasks:
  - name: test connection
      ping:
        
  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
      
  - name: Install list of packages
    apt: name={{item}} state=installed
    with_items:
        - nginx
        - git
        - tmux
        - screen
        - openjdk-8-jre
