---
- hosts: all
  remote_user: mark
  become: yes
  tasks:
  - name: run an apt update
    shell: apt update --yes
    ignore_errors: True
  - name: run an apt upgrade
    shell: apt upgrade --yes
    ignore_errors: True

  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes